### ISSUE TITLE
Where is the Code for "Integration with the Attention Mechanism and Offline Matrix Fusion"?

### ISSUE THREAD

**Issue by xlim1996** [shadowpa0327/Palu#6]
Hi,

First of all, thank you for your excellent work on this project. I’ve been exploring the code, and I’m particularly interested in understanding the part where Palu absorbs the reconstruction matrix of value Bv into the output projection matrix W_o offline.

Could you please point me to the specific section of the code that handles this?

Thanks in advance for your help!

Best regards,
Lucas

**Comment by shadowpa0327** [comment]
Hi @xlim1996! 

Thank you for your interest in our work. We are still working on refactoring our current implementations. Currently, the fusion of Bv into W_o is placed at [kernel/palu_attention.py#L285](https://github.com/shadowpa0327/Palu/blob/master/kernel/palu_attention.py#L285C9-L285C21). The testing code is over [here](https://github.com/shadowpa0327/Palu/blob/master/kernel/test_palu_attention.py#L135). Please let me know if you have further questions. 

Thank you
